// Generated by gencpp from file range_sensors_validator/sensor_properties.msg
// DO NOT EDIT!


#ifndef RANGE_SENSORS_VALIDATOR_MESSAGE_SENSOR_PROPERTIES_H
#define RANGE_SENSORS_VALIDATOR_MESSAGE_SENSOR_PROPERTIES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace range_sensors_validator
{
template <class ContainerAllocator>
struct sensor_properties_
{
  typedef sensor_properties_<ContainerAllocator> Type;

  sensor_properties_()
    : Quality(0)
    , sensor_values(0.0)
    , field_of_view(0.0)
    , min_range(0.0)
    , max_range(0.0)
    , range(0.0)  {
    }
  sensor_properties_(const ContainerAllocator& _alloc)
    : Quality(0)
    , sensor_values(0.0)
    , field_of_view(0.0)
    , min_range(0.0)
    , max_range(0.0)
    , range(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _Quality_type;
  _Quality_type Quality;

   typedef float _sensor_values_type;
  _sensor_values_type sensor_values;

   typedef float _field_of_view_type;
  _field_of_view_type field_of_view;

   typedef float _min_range_type;
  _min_range_type min_range;

   typedef float _max_range_type;
  _max_range_type max_range;

   typedef float _range_type;
  _range_type range;





  typedef boost::shared_ptr< ::range_sensors_validator::sensor_properties_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::range_sensors_validator::sensor_properties_<ContainerAllocator> const> ConstPtr;

}; // struct sensor_properties_

typedef ::range_sensors_validator::sensor_properties_<std::allocator<void> > sensor_properties;

typedef boost::shared_ptr< ::range_sensors_validator::sensor_properties > sensor_propertiesPtr;
typedef boost::shared_ptr< ::range_sensors_validator::sensor_properties const> sensor_propertiesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::range_sensors_validator::sensor_properties_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::range_sensors_validator::sensor_properties_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::range_sensors_validator::sensor_properties_<ContainerAllocator1> & lhs, const ::range_sensors_validator::sensor_properties_<ContainerAllocator2> & rhs)
{
  return lhs.Quality == rhs.Quality &&
    lhs.sensor_values == rhs.sensor_values &&
    lhs.field_of_view == rhs.field_of_view &&
    lhs.min_range == rhs.min_range &&
    lhs.max_range == rhs.max_range &&
    lhs.range == rhs.range;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::range_sensors_validator::sensor_properties_<ContainerAllocator1> & lhs, const ::range_sensors_validator::sensor_properties_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace range_sensors_validator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::range_sensors_validator::sensor_properties_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::range_sensors_validator::sensor_properties_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::range_sensors_validator::sensor_properties_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::range_sensors_validator::sensor_properties_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::range_sensors_validator::sensor_properties_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::range_sensors_validator::sensor_properties_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::range_sensors_validator::sensor_properties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1686b85e88ed009bf763d8dda0ab2b47";
  }

  static const char* value(const ::range_sensors_validator::sensor_properties_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1686b85e88ed009bULL;
  static const uint64_t static_value2 = 0xf763d8dda0ab2b47ULL;
};

template<class ContainerAllocator>
struct DataType< ::range_sensors_validator::sensor_properties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "range_sensors_validator/sensor_properties";
  }

  static const char* value(const ::range_sensors_validator::sensor_properties_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::range_sensors_validator::sensor_properties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 Quality\n"
"float32 sensor_values\n"
"float32 field_of_view\n"
"float32 min_range\n"
"float32 max_range\n"
"float32 range\n"
"\n"
;
  }

  static const char* value(const ::range_sensors_validator::sensor_properties_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::range_sensors_validator::sensor_properties_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Quality);
      stream.next(m.sensor_values);
      stream.next(m.field_of_view);
      stream.next(m.min_range);
      stream.next(m.max_range);
      stream.next(m.range);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sensor_properties_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::range_sensors_validator::sensor_properties_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::range_sensors_validator::sensor_properties_<ContainerAllocator>& v)
  {
    s << indent << "Quality: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Quality);
    s << indent << "sensor_values: ";
    Printer<float>::stream(s, indent + "  ", v.sensor_values);
    s << indent << "field_of_view: ";
    Printer<float>::stream(s, indent + "  ", v.field_of_view);
    s << indent << "min_range: ";
    Printer<float>::stream(s, indent + "  ", v.min_range);
    s << indent << "max_range: ";
    Printer<float>::stream(s, indent + "  ", v.max_range);
    s << indent << "range: ";
    Printer<float>::stream(s, indent + "  ", v.range);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RANGE_SENSORS_VALIDATOR_MESSAGE_SENSOR_PROPERTIES_H
